config/routes.rb
Spree::Core::Engine.routes.draw do
  
  match '/admin/reports/daily_orders' => 'admin/reports#daily_orders',
    via: [:get, :post],
    as:  'daily_orders_admin_reports'

  match '/admin/reports/all_orders' => 'admin/reports#all_orders', 
    via: [:get, :post], 
    as: 'all_orders_admin_reports'
    
end

app/controllers/spree/admin/reports_controller_decorator.rb
Spree::Admin::ReportsController.class_eval do
  
  ADDITIONAL= {
    sales_total: {name: 'Sales Total', description: 'Sales Total For All Orders' },
    daily_orders: {name: 'Daily Orders', description: 'CSV download of all orders for given date' }, 
    all_orders: {name: 'All Orders', description: "All Orders"}
  }

  Spree::Admin::ReportsController::AVAILABLE_REPORTS.merge!(ADDITIONAL)  
  
  def daily_orders
    respond_to do |format|
      format.html { render }
      format.csv { 
        delivery_date = params[:delivery_date] || Time.now.strftime("%Y/%m/%d")
        shipments = Spree::Shipment.where(scheduled_for: delivery_date)
        
        if shipments.size == 0
          flash[:notice] = "No Orers for #{delivery_date}"
          redirect_to daily_orders_admin_reports_url
          return
        end    
        
        file = Spree::Order.to_csv_for_download(delivery_date)

        # use Spree::Order class methods from JuiceShop spree site 
        send_data file, filename: "website_orders_#{delivery_date}.csv"
      }
    end
  end

  def all_orders
    respond_to do |format|
      format.html { render }
      format.csv { send_data Spree::Order.to_csv_for_download_all, filename: "website_orders_all.csv" }
    end
  end
end

app/views/spree/admin/reports/all_orders.html.erb
<% content_for :page_title do %>
  <%= t(:all_orders) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-arrow-left', t(:back_to_reports_list), spree.admin_reports_url, :class => 'button' %></li>
<% end %>

<br>

<%= link_to "Download All Orders", all_orders_admin_reports_url(format: 'csv'), {method: :get, class: 'button'}  %>

app/views/spree/admin/reports/daily_orders.html.erb
<% content_for :page_title do %>
  <%= t(:daily_deliveries) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-arrow-left', t(:back_to_reports_list), spree.admin_reports_url, :class => 'button' %></li>
<% end %>


<br>

<% [-1, 0, 1, 2, 3].each do |relative_day| %>
  <% time = Time.now + relative_day.days %>
  <% time_string = time.strftime("%Y/%m/%d") %>
  <% time_url_encoded = URI.encode(time_string) %>
  
  <% link_text = time_string %>
  <% link_text = "Today" if relative_day == 0 %>
  <% link_text = "Tomorrow" if relative_day == 1 %>  
  
  
  <%= link_to link_text, daily_orders_admin_reports_url(delivery_date: time_string, format: 'csv'), {method: :get, class: 'button'}  %>
<% end %>

<br>
<br>
<br>

<%= form_tag '/admin/reports/daily_orders.csv' do |s| %>
    <div class="date-range-filter field align-left">
        
        <%= text_field_tag :delivery_date, '', :class => 'datepicker' %>
         &nbsp;&nbsp;
        <%= label_tag nil, 'Delivery Date', :class => 'inline' %>
    </div>

    <div class="actions filter-actions">
      <%= button 'Download CSV', 'icon-search'  %>
    </div>
<% end %>